### ISSUE TITLE
Function execution fails in Ganache, succeeds in Remix' JS VM

### ISSUE THREAD

**Issue by nikita-fuchs** [ConsenSys-archive/ganache-ui#977]
## Issue

A function is executable in Remixs' JS EVM, but failing in Ganache

## Steps to Reproduce

1. deploy following contract: 
```
pragma solidity ^0.4.24;

// by (c) Nikita Fuchs - FOXUNIT OÜ

contract LEth {
    
    address[5] public recipients; 
    uint256 public counter; 
    
    event payment(bytes32 indexed _id, uint256 indexed counter);

    constructor (address[5] _recipients) public {
        recipients = _recipients;
        counter = 5;
    }

    function pay(bytes32 _id) public payable {
        require (msg.value > 0, "No value sent");
        ++counter;
        uint256 index = counter % 5;
        emit payment(_id, counter);
        recipients[index].transfer(msg.value);
    }
}
```
1.5 point remix to ganache

2. Execute ```pay () ```with "0xcafe" as parameter and provide some ```value```

## Expected Behavior

It would succeed both times.

## Actual Results

It fails only in ganache, cannot debug.

## Environment

* Operating System: OSX
* Ganache version: 1.2.2

**Comment by nikita-fuchs** [comment]
Found the culprit: When commenting out 
```recipients[index].transfer(msg.value) ```
it works - but what's the matter with that ?

**Comment by davidmurdoch** [comment]
Thanks @nikita-fuchs for reporting this issue. What error message are you receiving, if any?

**Comment by nikita-fuchs** [comment]
Hey, out of gas - I somehow suppose he gets out of bounds in the array?

Am Sa., 24. Nov. 2018, 20:11 hat David Murdoch <notifications@github.com>
geschrieben:

**Comment by davidmurdoch** [comment]
Possibly related to https://github.com/trufflesuite/ganache-cli/issues/585

**Comment by nikita-fuchs** [comment]
Are there any updates on this manner? I'm not a stack trace pro, but it should be possible to find some wrong jump pretty easy in this one ? Thanks for your efforts !

**Comment by rpsnoopy** [comment]
I have a similar case, where a payable fallback in a multi contract application fail on ganache with some VM fail and revert on ganache, works flawlessly on remix VM and Ropsten. I cannot share the code, but underline the importance of this bug. Tested on 1.22 and latest beta (2.01?)

**Comment by davidmurdoch** [comment]
@rpsnoopy My hunch right now is that this is an OOG error related to EIP-150, but am not certain. We're in the midst of improving our gas estimates to properly handle EIP-150and I suspect that these improvements will also fix things here (we'll also add tests to handle the above case to be sure we don't regress in the future).

**Comment by rpsnoopy** [comment]
@davidmurdoch thank you for the answer. Have you any rough idea about timeline of improvement? At the moment it is truly uncomfortable to develop under ganache finding bugs in the code, given that it can fail for the ganache internal error as well. We are in a near deploy phase and time run fast for us.

**Comment by rpsnoopy** [comment]
BTW I tested yesterday vs. 1.2.1 and the error is there as well.

Are there some possibilities that you fixed this in 1.2.3 (that apparently jumped out this night on releases page https://github.com/trufflesuite/ganache/releases/tag/v1.2.3)?

**Comment by davidmurdoch** [comment]
@rpsnoopy, the EIP-150 bug is not yet fixed in Ganache v1.2.3, Ganache v2.0.0-beta.2, or ganache-core yet.

**Comment by rpsnoopy** [comment]
Thank you for the news.

**Comment by davidmurdoch** [comment]
@rpsnoopy this bug should now be fixed in latest beta of ganache-cli and ganache-core

**Comment by rpsnoopy** [comment]
Thank you!Rick---- On Fri, 22 Mar 2019 02:37:57 +0100  David Murdoch<notifications@github.com> wrote ----@rpsnoopy this bug should now be fixed in latest beta of ganache-cli and ganache-core  —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by rpsnoopy** [comment]
Thank you David! We’ll test it in a week or two and I will be back to you with results!Rick---- On Thu, 28 Mar 2019 18:26:34 +0100  David Murdoch<notifications@github.com> wrote ----This should now be fixed in the latest beta tagged releases of ganache-cli and ganache-core. This fix involved pretty significant code changes; check out the release notes for details. We'd love it if you'd test this beta out to make sure things are good to go before we release to stable. If you using ganache-cli, run: npm install -g ganache-cli@beta If you are using ganache-core, run: npm install ganache-core@beta Let us know if you discover any bugs with this new beta release! Thanks!  —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
